### ISSUE TITLE
why is crew a required submission field?

### ISSUE THREAD

**Issue by boguwei** [nasa/uam-apis#16]
https://github.com/nasa/uam-apis/blob/957b05e55572673aa84fafac9500590302dd9ee2/datacollection/openapi/X3/uam-data-collection-X3.yaml#L401

we'll be running in simulation anyway. even if the pilots weren't simulated, I don't think we would be comfortable sharing that PII across this exchange. would it be reasonable to just provide dummy data here, or do the values here actually have a functional impact on the metrics being calculated?

**Comment by mohanagurram** [comment]
The only required field within CrewMember object is the "role", remaining fields are optional.

**Comment by boguwei** [comment]
thanks for the clarification.
